'''
Given a keypad as shown in the diagram, and an array arr[ ], your task is to list all possible words in any order which can be generated by pressing numbers from array.



Examples :

Input: arr[] = [2, 3]
Output: ad ae af bd be bf cd ce cf
Explanation: When we press 2, 3 total possible words are 3 x 3 = 9.
Input: arr[] =[3, 4, 5]
Output: dgj dgk dgl dhj dhk dhl dij dik dil egj egk egl ehj ehk ehl eij eik eil fgj fgk fgl fhj fhk fhl fij fik fil
Explanation: When we press 3, 4, 5 total possible words are 3 x 3 x 3 = 27.
Input: arr[] =[2]
Output: a b c
Explanation: When we press 2 total possible words are 3.
Constraints:
1 ≤ arr.size() ≤ 10
2 ≤ arr[i] ≤ 9
'''

class Solution:
    def possibleWords(self, numbers):
        kp={2:"abc",3:"def",4:"ghi",5:"jkl",6:"mno",7:"pqrs",8:"tuv",9:"wxyz"}
        
        def bt(i,p):
            if i==len(numbers):
                result.append("".join(p))
                return
            
            for ch in kp[numbers[i]]:
                p.append(ch)
                bt(i+1,p)
                p.pop()
                
        result=[]
        if not numbers:
            return result
            
        bt(0,[])
        return result

